name: Update README all day at 01:00

on:
  push:
  workflow_dispatch:
  schedule:
    # “Update at 1:00”
    - cron: '0 1 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js > README.md
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: AzaleeX
          author_email: azaleemcpe@gmail.com
          force: false
          signoff: false
          message: ':memo: README.md updated by ZaeleeBot'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}